name: Create Trello Card When Issue Created

on:
  issues:
    types: [opened]

jobs:
  link_with_trello:
    name: Create Trello Card
    runs-on: ubuntu-latest
    steps:
    - name: Call trello-github-actions 
      id: call-trello-github-actions
      uses: Grabtot/trello-github-actions@master 
      with:
        trello-action: create_card_when_issue_opened
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
        TRELLO_TODO_LIST_ID: ${{ secrets.TRELLO_TODO_LIST_ID }}
        TRELLO_IN_PROGRESS_LIST_ID: ${{ secrets.TRELLO_IN_PROGRESS_LIST_ID }}
        TRELLO_DEBUGING_LIST_ID: ${{ secrets.TRELLO_DEBUGING_LIST_ID }}
        TRELLO_DONE_LIST_ID: ${{ secrets.TRELLO_DONE_LIST_ID }}
